### ISSUE TITLE
Fix incorrect wording in Hotfix documentation

### ISSUE THREAD

**Issue by Aaquiff** [wso2/docs-updates#111]
The highlighted wording in the following sentence is incorrect and needs to be changed.

3. Having a single issue to be addressed and `needs to be push the production` environment soon. Reporting an issue and receiving a hotfix saves you time and trouble.

This needs to be changed to `needs to be pushed to the production`.

Location : https://updates.docs.wso2.com/en/latest/updates/hotfixes/

**Comment by chamindi-a** [comment]
Resolve #110

**Comment by chamindi-a** [comment]
#110

**Comment by chamindi-a** [comment]
#110

**Comment by chamindi-a** [comment]
#110
