### ISSUE TITLE
Page navigation disappears when user scrolls down

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/docs-updates#132]
**Description:**
In doc [1], when you scroll down and go up again the navigation and the ToC are lost. 
A page refresh will bring back the navigation and ToC.

**Reproduce the issue:**
1. Go to [1].
2. Scroll down the page.
3. Scroll up to the top again. The Nav and ToC will no longer be visible.
4. Refresh the page. The Nav and ToC appear.

Browser: Chrome

[1] https://updates.docs.wso2.com/en/latest/updates/update-tool/

**Comment by chamindi-a** [comment]
Resolve #136

**Comment by divyaamunugama** [comment]
Changes verified in public doc space. Working as expected.
