### ISSUE TITLE
Review Warning/ Critical IS MsSQL Identity DB Storage Percentage Limit Exceeded runbook

### ISSUE THREAD

**Issue by chamindi-a** [wso2/docs-updates#134]

**Comment by chamindi-a** [comment]
i have completed an initial review on this runbook and have added some comments for @WickramBug to resolve, will check on the same when issue posted are cleared.

**Comment by WickramBug** [comment]
I have updated the document with recommended changes. Please check and finalize @chamindi-a

**Comment by chamindi-a** [comment]
Closing the issues because above issues is closed
