### ISSUE TITLE
Add information about 'what tool used to update', the product pack to Documentation site

### ISSUE THREAD

**Issue by chamindi-a** [wso2/docs-updates#137]

**Comment by chamindi-a** [comment]
@jsdjayanga  and I added the initial draft of the content to a gdoc
need to test the usecases and improve the steps

**Comment by Thimuth** [comment]
Updated the content in following pages in wso2.com

https://wso2.com/updates/wum/
https://wso2.com/wum/download/

**Comment by chamindi-a** [comment]
Draft gdoc: https://docs.google.com/document/d/1UQ01AKLcHLbWkl1xmn3w-A2i7539jb20BmEkfA17wGU/edit?hl=en&forcehl=1

**Comment by chamindi-a** [comment]
closing the issue after PR merge #141
