### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by ggianoglio** [wso2/docs-updates#22]
Location : https://updates.docs.wso2.com/en/latest/updates/continuous-update/

The link in `Need to further refer WSO2 recommended Puppet and Ansible, Click Here.` https://updates.docs.wso2.com/en/latest/updates/updates/faq/#what-are-the-recommended-configuration-management-tools-to-deploy-configurations-to-client-nodes is broken (Page not found).

**Comment by chamindi-a** [comment]
Thank you for your input, I have corrected this issue and a PR is being added

**Comment by chamindi-a** [comment]
#21 has resolved the issue

**Comment by VimukthiPerera** [comment]
Closing as the issue is resolved by #24
