### ISSUE TITLE
Doc Feedback: how long is the trial subscription?

### ISSUE THREAD

**Issue by isharailanga** [wso2/docs-updates#36]
Location : https://updates.docs.wso2.com/en/latest/updates/faq/

what is the validity period of the trial subscription? the docs mention it as 90 days, and this [article](https://wso2.com/blogs/thesource/2018/03/new-free-trial-subscriptions-wso2-update-2-0-and-more/) says it's only 15 days.

**Comment by chamindi-a** [comment]
Hi Ishara,
This is a rather old article and our new EULA agreement states the Free trial for 90 days
Refer https://wso2.com/licenses/eula/3.1
Since the New documents clearly mention the duration we are able to resolve this issue

**Comment by chamindi-a** [comment]
@Savidude: Can you please close this issue, Thank you :)

**Comment by isharailanga** [comment]
Hi Chamindi,
Thank you for the clarifications. Closing the issue as the above comment clarifies the confusion.
