### ISSUE TITLE
Doc Feedback: Command to run the wso2update_linux script

### ISSUE THREAD

**Issue by isharailanga** [wso2/docs-updates#37]
Location : https://updates.docs.wso2.com/en/latest/updates/update-tool/

For Linux env, The Update tool does not run with the given command. 

![image](https://user-images.githubusercontent.com/14251853/118124072-b42a1580-b412-11eb-90b6-2b0ac68cb73e.png)

1. This command does not work. To run the script give the following command
`./wso2update_linux`

2. Also, it is better to mention for first time users, you need to run the same script again to get the packs updated.

**Comment by chamindi-a** [comment]
#40

**Comment by Savidude** [comment]
Resolved in  #56
