### ISSUE TITLE
No instructions for reverting an updated pack to previous state.

### ISSUE THREAD

**Issue by Prabhashi** [wso2/docs-updates#41]
**Description:**
In the Update 2.0 documentation[1], we could see that we have slightly mentioned about revert process as below however the relevant commands `./wso2update_<OS> --revert` can not be found there. Also the revert commands can not be seen in the update-commands list[2] page as well.

![image](https://user-images.githubusercontent.com/28176167/119080172-34560980-ba17-11eb-85eb-5f52430c7f61.png)

[1] https://updates.docs.wso2.com/en/latest/updates/update-tool/
[2] https://updates.docs.wso2.com/en/latest/updates/update-commands/

**Suggested Labels:**

Update 2.0

**Suggested Assignees:**

**Comment by chamindi-a** [comment]
#49

**Comment by Savidude** [comment]
Fixed in #49
